// backend/src/routes/reports.js
const express = require('express');
const fs = require('fs');
const path = require('path');
const jwt = require('jsonwebtoken');
const puppeteer = require('puppeteer');
const PDFDocument = require('pdfkit');

const router = express.Router();
const JWT_SECRET = process.env.JWT_SECRET || 'dev_jwt_secret';

const reportsDir = path.join(__dirname, '..', '..', 'storage', 'reports');
if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

// optional logo embed - put an image at backend/assets/pravah_logo.png if you want logo in PDFs
const logoPath = path.join(__dirname, '..', '..', 'assets', 'pravah_logo.png');
let logoDataUrl = '';
try {
  const buf = fs.readFileSync(logoPath);
  logoDataUrl = `data:image/png;base64,${buf.toString('base64')}`;
} catch (e) {
  console.warn('Logo missing or unreadable, continuing without logo:', e.message);
}

function cssStyles() {
  return `<style>
    body{font-family: Arial, sans-serif; color:#222; margin:18px}
    header{display:flex; align-items:center; gap:12px; margin-bottom:12px}
    header img{width:64px;height:64px}
    h1{font-size:18px;margin:0}
    table{width:100%; border-collapse:collapse; margin-top:8px}
    th, td{border:1px solid #ddd; padding:8px; text-align:left; font-size:12px}
    th{background:#f2f7f9}
    .small{font-size:11px;color:#555}
  </style>`;
}

function buildCombinedHtml(diary, students, attendance) {
  const presentIds = new Set(attendance.map(a => a.student_id));
  const attendanceRows = students.map((s, idx) => {
    const present = presentIds.has(s.student_id) ? 'Present' : 'Absent';
    return `<tr><td>${idx+1}</td><td>${s.student_id}</td><td>${s.name}</td><td>${s.class||''}</td><td>${present}</td></tr>`;
  }).join('');

  const volunteersHtml = (diary.volunteer_reports || []).map((v,i) => `
    <tr><td>${i+1}</td><td>${v.volunteer_name||v.volunteer_id||''}</td>
      <td>${v.in_time||''} - ${v.out_time||''}</td><td>${v.subject_taught||''}</td>
      <td>${v.topic||''}</td><td>${v.students_present||''}</td></tr>`).join('');

  return `<!doctype html><html><head><meta charset="utf-8">${cssStyles()}</head><body>
    <header>
      ${logoDataUrl ? `<img src="${logoDataUrl}" alt="Pravah" />` : ''}
      <div><h1>UPAY Daily Centre Report</h1><div class="small">${diary.center_id} • ${diary.date}</div></div>
    </header>

    <section>
      <h3>Diary Summary</h3>
      <table>
        <tr><th>Prepared by</th><td>${diary.prepared_by?.name || diary.prepared_by || ''}</td></tr>
        <tr><th>In Time</th><td>${diary.in_time || ''}</td></tr>
        <tr><th>Out Time</th><td>${diary.out_time || ''}</td></tr>
        <tr><th>Thought</th><td>${diary.thought || ''}</td></tr>
        <tr><th>Remarks</th><td>${diary.remarks || ''}</td></tr>
      </table>
    </section>

    <section>
      <h3>Daily Checklist</h3>
      <table><tbody>
      ${Object.entries(diary.daily_checklist || {}).map(([k,v]) => `<tr><th>${k.replace(/_/g,' ')}</th><td>${v ? 'Yes' : 'No'}</td></tr>`).join('')}
      </tbody></table>
    </section>

    <section>
      <h3>Volunteer Reports</h3>
      <table><thead><tr><th>#</th><th>Name</th><th>In-Out</th><th>Subject</th><th>Topic</th><th>Students</th></tr></thead>
      <tbody>${volunteersHtml}</tbody></table>
    </section>

    <section>
      <h3>Attendance</h3>
      <div>Total enrolled: ${students.length} • Present: ${attendance.length}</div>
      <table><thead><tr><th>#</th><th>Student ID</th><th>Name</th><th>Class</th><th>Status</th></tr></thead>
      <tbody>${attendanceRows}</tbody></table>
    </section>

    <footer style="margin-top:18px"><div class="small">Generated by Pravah • ${new Date().toLocaleString()}</div></footer>
  </body></html>`;
}

// Simple pdfkit fallback (text-based)
function generatePdfWithPdfKitPlain(diary, students, attendance, outPath) {
  const doc = new PDFDocument({ margin: 18, size: 'A4' });
  doc.pipe(fs.createWriteStream(outPath));
  doc.fontSize(16).text('UPAY Daily Centre Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).text(`Center: ${diary.center_id || ''}   Date: ${diary.date || ''}`);
  doc.moveDown();
  doc.fontSize(12).text(`Prepared by: ${diary.prepared_by?.name || diary.prepared_by || ''}`);
  doc.moveDown();
  doc.text(`In Time: ${diary.in_time || ''}   Out Time: ${diary.out_time || ''}`);
  doc.moveDown();
  doc.text('Daily Checklist:');
  Object.entries(diary.daily_checklist || {}).forEach(([k,v]) => {
    doc.text(`${k.replace(/_/g,' ')} : ${v ? 'Yes' : 'No'}`);
  });
  doc.moveDown();
  doc.text('Volunteer Reports:');
  (diary.volunteer_reports || []).forEach((vr, i) => {
    doc.text(`${i+1}. ${vr.volunteer_name || vr.volunteer_id || ''} | In:${vr.in_time || ''} Out:${vr.out_time || ''} | ${vr.subject_taught || ''}`);
  });
  doc.moveDown();
  doc.text('Attendance Summary:');
  doc.text(`Enrolled: ${students.length}  Present: ${attendance.length}`);
  doc.end();
}

// auth middleware
function authMiddleware(req, res, next) {
  const auth = req.headers.authorization || '';
  if (!auth.startsWith('Bearer ')) return res.status(401).json({ error: 'Missing token' });
  try {
    req.user = jwt.verify(auth.slice(7), JWT_SECRET);
    next();
  } catch (e) { return res.status(401).json({ error: 'Invalid token' }); }
}

// GET list of reports for a center
const reportsFile = path.join(__dirname, '..', '..', 'db', 'seed', 'reports.json');
if (!fs.existsSync(reportsFile)) fs.writeFileSync(reportsFile, '[]', 'utf8');

router.get('/list', authMiddleware, (req, res) => {
  const center = req.query.center;
  try {
    const reports = JSON.parse(fs.readFileSync(reportsFile,'utf8') || '[]');
    const out = center ? reports.filter(r => r.center_id === center) : reports;
    res.json({ reports: out });
  } catch (e) {
    console.error('reports read error', e);
    res.status(500).json({ error: 'Could not read reports' });
  }
});

// Download endpoint
router.get('/download', authMiddleware, (req, res) => {
  const file = req.query.file;
  if (!file) return res.status(400).json({ error: 'file query param required' });
  const p = path.join(reportsDir, path.basename(file));
  if (!fs.existsSync(p)) return res.status(404).json({ error: 'report not found' });
  res.download(p);
});

// Combined pdf generator route
// POST /api/diary/generate-combined
// Body: diary JSON as described in your plan
router.post('/diary/generate-combined', authMiddleware, async (req, res) => {
  try {
    const diary = req.body || {};
    if (!diary.center_id || !diary.date) return res.status(400).json({ error: 'center_id and date required' });

    // load students & attendance
    const studentsFile = path.join(__dirname, '..', '..', 'db', 'seed', 'students.json');
    const attFile = path.join(__dirname, '..', '..', 'db', 'seed', 'attendance.json');
    const students = fs.existsSync(studentsFile) ? JSON.parse(fs.readFileSync(studentsFile,'utf8')||'[]') : [];
    const attendance = fs.existsSync(attFile) ? JSON.parse(fs.readFileSync(attFile,'utf8')||'[]') : [];

    const centerStudents = students.filter(s => s.center_id === diary.center_id);
    const centerAttendance = attendance.filter(a => a.center_id === diary.center_id && a.date === diary.date);

    const html = buildCombinedHtml(diary, centerStudents, centerAttendance);

    const filename = `${diary.center_id}_diary_attendance_${diary.date}.pdf`.replace(/[^a-zA-Z0-9_\-\.]/g,'_');
    const outPath = path.join(reportsDir, filename);

    // Try Puppeteer first
    try {
      const browser = await puppeteer.launch({ args: ['--no-sandbox','--disable-setuid-sandbox'] });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      await page.pdf({ path: outPath, format: 'A4', printBackground: true });
      await browser.close();
    } catch (puppErr) {
      console.error('Puppeteer render failed, falling back to pdfkit:', puppErr && puppErr.message ? puppErr.message : puppErr);
      generatePdfWithPdfKitPlain(diary, centerStudents, centerAttendance, outPath);
    }

    // Save metadata
    const reports = JSON.parse(fs.readFileSync(reportsFile,'utf8') || '[]');
    reports.push({ file: filename, center_id: diary.center_id, type: 'diary_attendance', date: diary.date, created_at: new Date().toISOString(), created_by: req.user.volunteer_id || req.user.name || 'unknown' });
    fs.writeFileSync(reportsFile, JSON.stringify(reports, null, 2), 'utf8');

    return res.json({ ok: true, file: filename, path: `storage/reports/${filename}` });
  } catch (err) {
    console.error('generate-combined error', err);
    return res.status(500).json({ error: 'Could not generate combined report' });
  }
});

module.exports = router;
