import React, { useEffect, useState } from "react";
import { useLocation, useParams } from "react-router-dom";
import "./DiaryPreview.css";

export default function DiaryPreview({ token }) {
  const { id } = useParams(); // optional
  const loc = useLocation();
  const [diary, setDiary] = useState(loc.state?.diary || null);

  useEffect(() => {
    async function fetchDiary() {
      if (!diary && id) {
        try {
          const res = await fetch(`/api/diary/${encodeURIComponent(id)}`, { headers: { Authorization: "Bearer " + token } });
          if (!res.ok) throw new Error("Fetch failed");
          const data = await res.json();
          setDiary(data.savedDiary || data);
        } catch (e) {
          console.error(e);
        }
      }
    }
    fetchDiary();
  }, [id, diary, token]);

  if (!diary) return <div>Loading...</div>;

  const handlePrint = () => window.print();

  return (
    <div>
      <div className="no-print" style={{ marginBottom: 12 }}>
        <button onClick={handlePrint}>Print / Save as PDF</button>
      </div>

      <div className="diary-print-area">
        <header className="diary-header">
          <h2>UPAY Daily Centre Report / Diary</h2>
          <div>{diary.center_id} • {diary.date}</div>
          <div>Prepared by: {diary.prepared_by?.name} ({diary.prepared_by?.volunteer_id})</div>
        </header>

        <section className="summary">
          <table>
            <tbody>
              <tr><th>Total enrolled</th><td>{diary.total_enrolled}</td></tr>
              <tr><th>Present today</th><td>{diary.present_count}</td></tr>
              <tr><th>In time</th><td>{diary.in_time}</td></tr>
              <tr><th>Out time</th><td>{diary.out_time}</td></tr>
            </tbody>
          </table>
        </section>

        <section className="checklist">
          <h4>Daily Checklist</h4>
          <ul>
            {Object.entries(diary.daily_checklist || {}).map(([k,v]) => (
              <li key={k}>{k.replace(/_/g,' ')} : {v ? "Yes" : "No"}</li>
            ))}
          </ul>
        </section>

        <section className="volunteers">
          <h4>Volunteer Reports</h4>
          { (diary.volunteer_reports || []).map((r, i) => (
            <div key={i} className="vol-row">
              <div><strong>{r.volunteer_name} ({r.volunteer_id})</strong></div>
              <div>In: {r.in_time} Out: {r.out_time}</div>
              <div>Subject: {r.subject_taught} | Topic: {r.topic}</div>
              <div>Homework: {r.homework} | Students: {r.students_present}</div>
            </div>
          )) }
        </section>

        <section className="attendance-table">
          <h4>Attendance Summary</h4>
          <table>
            <thead><tr><th>#</th><th>Student ID</th><th>Name</th><th>Class</th><th>Present</th></tr></thead>
            <tbody>
              {(diary.attendance_list || []).map((s, idx) => (
                <tr key={s.student_id || idx}>
                  <td>{idx+1}</td>
                  <td>{s.student_id}</td>
                  <td>{s.name}</td>
                  <td>{s.class}</td>
                  <td>{s.present ? "Yes" : "No"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <section className="remarks"><h4>Remarks</h4><div>{diary.remarks}</div></section>

        <footer className="diary-footer">
          <div>Signature: {diary.signature}</div>
          <div className="small">Generated by Pravah • {new Date().toLocaleString()}</div>
        </footer>
      </div>
    </div>
  );
}
